baseurl = ""
title = "Lenny Kiruthu"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 10 #frontpage pagination
hasCJKLanguage = false
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "docs"

[outputs]
home = ["HTML", "RSS"]

[params]
  header_image = "images/banner/homepage_banner.webp"
  SEOTitle = "Leading with Innovation"
  description = "Lenny Kiruthu, Data Science, Algorithmic Trader, Life Explorer."
  keyword = "Eric, eric, Eric's Blog, Web, PaaS, SaaS, Kubernetes, Microservice, Docker, Linux, Open-Source, DevOps"
  slogan = "Leading with Innovation"
  image_404 = "images/404/404.webp"
  title_404 = "You came to the wasteland without knowledge :("
  omit_categories = false

  # Sidebar settings
  sidebar_about_description = "Unlocking insights through code and data. Join me on a journey of transforming complex algorithms into actionable intelligence as I strive to become a quantitative developer and aspiring data scientist."
  sidebar_avatar = "images/about_me/lenny_profile_picture.webp"      # use absolute URL, seeing it's used in both `/` and `/about/`
  featured_tags = true
  featured_condition_size = 1
  support_button = false
  friends = false
  bookmarks = false
  about_me = true

  [params.social]
  rss            = false 
  email          = "kiruthulenny@gmail.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  linkedin       = "https://www.linkedin.com/in/lenny-kiruthu"
  # stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  # github         = "https://github.com/ErikNgigi"
  # wechat         = "your wechat qr code image"
  #medium        = "full profile url in medium"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"

  # [[params.addtional_menus]]
  # title =  "Templates"
  # href =  "/more/templates/"
  [[params.addtional_menus]]
  title =  "Portfolio"
  href =  "/more/portfolio/"
  [[params.addtional_menus]]
  title = "Pitch"
  href = "/more/pitch/"
  [[params.addtional_menus]]
  title =  "About"
  href =  "/more/about/"

  [markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1
  [markup.highlight]
    style = "dracula"
